// SSE streaming for chat completions — ds4 buffer-and-resplit model.
//
// The caller accumulates ALL generated bytes into one buffer and calls
// ember_sse_update() after each token with the full buffer so far. The stream
// re-scans from its emit watermark every call, so a `<think>`/`</think>` tag, a
// tool marker, or a multi-byte codepoint split across ANY number of tokens is
// always re-findable and never partially emitted. This is the opposite of an
// incremental window state machine (which loses context once it trims) and is
// why it is correct by construction rather than by accumulated patches.
#ifndef EMBER_SSE_H
#define EMBER_SSE_H

#include <stdbool.h>
#include <stddef.h>
#include "../common/buf.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
    EMBER_SSE_THINKING,  // inside <think>...</think> → reasoning_content deltas
    EMBER_SSE_TEXT,      // visible assistant text → content deltas
    EMBER_SSE_TOOL,      // a tool-call marker was seen → suppress from content
    EMBER_SSE_SUPPRESS   // terminal: emit nothing further as content/reasoning
} ember_sse_mode;

typedef struct {
    // config (set by ember_sse_init)
    char        *id;              // chatcmpl id (owned)
    char        *model;           // model name (owned)
    long         created;         // unix ts for the `created` field
    bool         has_tools;       // request declared tools
    bool         enable_cors;
    bool         include_usage;   // stream_options.include_usage (gate usage chunk)
    int          cached_tokens;   // restored prefix length → prompt_tokens_details
    char *const *stops;           // client stop strings (borrowed; NULL if none)
    int          n_stops;
    int          max_stop_len;    // longest stop string (for content holdback)

    // state
    ember_sse_mode mode;
    size_t       emit_pos;        // bytes of `raw` already emitted
    bool         checked_think_prefix;
    bool         sent_reasoning;
    bool         sent_content;
    size_t       tool_start;      // offset in raw where a tool marker began
    // incremental tool-call streaming state
    int          tool_idx;        // highest tool_call index started (-1 = none)
    int          tool_nparams;    // args fragments emitted for the current call
    bool         tool_open;       // current call's args object needs a closing "}"
    bool         any_tool;        // at least one tool_call was streamed
    // B3: the minted ids for streamed tool calls, so the caller can store the
    // exact sampled bytes under them (exact-DSML replay). Owned; freed in _free.
    char        *tool_ids[16];
    int          n_tool_ids;
} ember_sse_stream;

// Initialize. `started_in_thinking` reflects a prompt that ends inside <think>
// (DeepSeek with thinking enabled): the model's first bytes are reasoning.
void ember_sse_init(ember_sse_stream *st, const char *id, const char *model,
                    long created, bool has_tools, bool started_in_thinking,
                    bool enable_cors);

void ember_sse_free(ember_sse_stream *st);

// Emit the HTTP + SSE response headers into `out`. Call once before any data.
void ember_sse_headers(ember_buf *out, bool enable_cors);

// A `: prefill` keepalive comment (ds4 server_prefill_progress). Emit every few
// seconds while prefill runs so streaming clients don't idle-timeout.
void ember_sse_keepalive(ember_buf *out);

// Emit the initial {delta:{role:"assistant"}} primer chunk (ds4 sse_chunk role
// primer). Call once after headers, before any content/reasoning delta.
void ember_sse_role_chunk(ember_sse_stream *st, ember_buf *out);

// Process the full accumulated `raw` buffer; append any newly-safe SSE delta
// lines to `out`. `final` releases all holdbacks at end-of-stream. Returns the
// updated emit watermark (also stored in st->emit_pos).
void ember_sse_update(ember_sse_stream *st, const char *raw, size_t raw_len,
                      bool final, ember_buf *out);

// If a tool marker was seen during the stream, parse the buffered tool region
// from `raw` and emit structured tool_calls deltas into `out`. Returns true if
// any tool call was emitted — the caller should then finish with "tool_calls".
bool ember_sse_emit_tools(ember_sse_stream *st, const char *raw, size_t raw_len,
                          ember_buf *out);

// Emit the terminal chunk (finish_reason) + optional usage + `data: [DONE]`.
void ember_sse_finish(ember_sse_stream *st, const char *finish_reason,
                      int prompt_tokens, int completion_tokens, ember_buf *out);

// Emit an `event: error` frame (ds4 sse_error_event) for a mid-stream backend
// failure, followed by `data: [DONE]`.
void ember_sse_error(ember_sse_stream *st, const char *code, const char *detail,
                     ember_buf *out);

// ── exposed for unit tests ──
// Largest safe content length in raw[start..raw_len): holds back an incomplete
// UTF-8 tail and, with tools, everything from the last '<' in the trailing scan
// window (any marker begins with '<'). Ported from ds4 text_stream_safe_limit.
size_t ember_text_safe_limit(const char *raw, size_t start, size_t raw_len,
                             bool has_tools, bool final);
// Earliest tool-call marker start in `s`, or NULL. Recognizes DeepSeek DSML in
// its full, short (leading '<|' eaten), and ascii-degraded spellings.
const char *ember_find_tool_start(const char *s);
// Byte after the earliest complete tool-calls END marker in `s`, or NULL.
const char *ember_find_tool_end(const char *s);

#ifdef __cplusplus
}
#endif

#endif  // EMBER_SSE_H
