// SSE streaming for chat completions — ds4 buffer-and-resplit model.
//
// The caller accumulates ALL generated bytes into one buffer and calls
// ember_sse_update() after each token with the full buffer so far. The stream
// re-scans from its emit watermark every call, so a `<think>`/`</think>` tag, a
// tool marker, or a multi-byte codepoint split across ANY number of tokens is
// always re-findable and never partially emitted. This is the opposite of an
// incremental window state machine (which loses context once it trims) and is
// why it is correct by construction rather than by accumulated patches.
#ifndef EMBER_SSE_H
#define EMBER_SSE_H

#include <stdbool.h>
#include <stddef.h>
#include "../common/buf.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
    EMBER_SSE_THINKING,  // inside <think>...</think> → reasoning_content deltas
    EMBER_SSE_TEXT,      // visible assistant text → content deltas
    EMBER_SSE_TOOL,      // tool marker seen → buffer until caller validates
    EMBER_SSE_SUPPRESS   // terminal: emit nothing further as content/reasoning
} ember_sse_mode;

// Protocol-neutral delta sink. The buffer-and-resplit parser owns framing
// safety and DSML parsing; a wire adapter owns the JSON event taxonomy.
// Leaving these callbacks unset preserves the OpenAI Chat Completions emitter.
typedef struct {
    void (*text_delta)(void *ud, bool reasoning,
                       const char *text, size_t len, ember_buf *out);
    void (*tool_start)(void *ud, int index, const char *id, const char *name,
                       ember_buf *out);
    void (*tool_args_delta)(void *ud, int index,
                            const char *text, size_t len, ember_buf *out);
} ember_sse_sink;

typedef struct {
    // config (set by ember_sse_init)
    char        *id;              // chatcmpl id (owned)
    char        *model;           // model name (owned)
    long         created;         // unix ts for the `created` field
    bool         has_tools;       // request declared tools
    bool         enable_cors;
    bool         include_usage;   // stream_options.include_usage (gate usage chunk)
    int          cached_tokens;   // restored prefix length → prompt_tokens_details
    int          prefill_tokens;  // prompt suffix actually evaluated by backend
    double       prefill_s;
    double       decode_s;
    double       accept_rate;
    const char  *prefill_mode;    // borrowed backend execution label
    const char  *prefill_reason;  // borrowed backend policy label
    const char  *termination_reason; // borrowed progress-watchdog cause, or ""
    bool         reasoning_budget_exhausted;
    bool         degenerate;
    // Request-derived diagnostic only. It never changes finish_reason or stops
    // generation; when nonzero it is emitted on the terminal choice object.
    int          tool_loop_rounds;
    // false when the count came from the weaker call-signature signal, i.e.
    // the calls repeated but their results did not.
    bool         tool_loop_identical;
    const char  *tool_loop_tool; // borrowed first tool name
    // Pre-rendered `"compaction":{...}` fragment (borrowed, no leading comma),
    // appended inside the usage object when set. A string rather than the report
    // struct so sse.c keeps no dependency on compaction.h.
    const char  *compaction_json;
    char *const *stops;           // client stop strings (borrowed; NULL if none)
    int          n_stops;
    int          max_stop_len;    // longest stop string (for content holdback)
    char        *reasoning_filter; // server-authored pre-</think> suffix (owned)
    size_t       reasoning_filter_len;

    // state
    ember_sse_mode mode;
    size_t       emit_pos;        // bytes of `raw` already emitted
    bool         checked_think_prefix;
    bool         sent_reasoning;
    bool         sent_content;
    bool         sent_visible_content;  // a non-whitespace content byte reached
                                        // the client; see
                                        // ember_sse_delivered_visible()
    size_t       tool_start;      // offset in raw where a tool marker began
    // validation-gated tool-call emission state
    int          tool_idx;        // highest tool_call index started (-1 = none)
    int          tool_nparams;    // args fragments emitted for the current call
    bool         tool_open;       // current call's args object needs a closing "}"
    bool         any_tool;        // at least one tool_call was streamed
    // B3: the minted ids for streamed tool calls, so the caller can store the
    // exact sampled bytes under them (exact-DSML replay). Owned; freed in _free.
    char       **tool_ids;
    int          n_tool_ids;
    int          tool_ids_cap;
    ember_sse_sink sink;          // optional protocol-native delta callbacks
    void        *sink_ud;         // borrowed for the stream lifetime
} ember_sse_stream;

// Initialize. `started_in_thinking` reflects a prompt that ends inside <think>
// (DeepSeek with thinking enabled): the model's first bytes are reasoning.
void ember_sse_init(ember_sse_stream *st, const char *id, const char *model,
                    long created, bool has_tools, bool started_in_thinking,
                    bool enable_cors);

void ember_sse_free(ember_sse_stream *st);

// Replace the default Chat Completions wire emitter with a protocol-native
// sink while retaining the same stream-safe reasoning/content/tool parser.
void ember_sse_set_sink(ember_sse_stream *st, const ember_sse_sink *sink,
                        void *ud);

// Hide a server-authored suffix that is injected immediately before </think>
// (for example the budget force-close directive) from reasoning deltas.
void ember_sse_set_reasoning_filter(ember_sse_stream *st, const char *hint);

// Start projecting a replacement model attempt on the same wire stream. This
// preserves protocol/configuration state and already-emitted ordinary text, but
// clears every raw-buffer cursor and uncommitted tool-call id. Call only when a
// hidden recovery replaced the generated buffer before any tool delta was sent.
void ember_sse_reset_attempt(ember_sse_stream *st, bool started_in_thinking);

// Emit the HTTP + SSE response headers into `out`. Call once before any data.
void ember_sse_headers(ember_buf *out, bool enable_cors);

// A `: prefill` keepalive comment (ds4 server_prefill_progress). Emit every few
// seconds while prefill runs so streaming clients don't idle-timeout.
void ember_sse_keepalive(ember_buf *out);

// Emit the initial {delta:{role:"assistant"}} primer chunk (ds4 sse_chunk role
// primer). Call once after headers, before any content/reasoning delta.
void ember_sse_role_chunk(ember_sse_stream *st, ember_buf *out);

// Process the full accumulated `raw` buffer; append any newly-safe SSE delta
// lines to `out`. `final` releases all holdbacks at end-of-stream. Returns the
// updated emit watermark (also stored in st->emit_pos).
void ember_sse_update(ember_sse_stream *st, const char *raw, size_t raw_len,
                      bool final, ember_buf *out);

// If a tool marker was seen, emit its buffered structured tool_calls deltas.
// The caller must invoke this only after the complete generated block passes
// structural, contamination, JSON, and schema validation. Returns true if any
// tool call was emitted — the caller should then finish with "tool_calls".
bool ember_sse_emit_tools(ember_sse_stream *st, const char *raw, size_t raw_len,
                          ember_buf *out);

// Close out a tool block that failed validation, without emitting it
// (ds4 openai_sse_stream_update:6449-6455).
//
// A malformed tool block is model output, not a server failure
// (ds4_server.c:5231-5241), so the turn must still finish normally rather than
// die at a typed error — a streaming agent cannot retry and would lose the
// whole round. The suppressed bytes are dropped rather than replayed as text:
// see the rationale in sse.c. Caller then finishes with
// ember_tool_parse_failure_finish().
//
// Only meaningful in EMBER_SSE_TOOL mode; returns true if it took effect.
bool ember_sse_discard_tool_block(ember_sse_stream *st, size_t raw_len);

// ds4 tool_parse_failure_recovery_finish (ds4_server.c:5194-5201): once DSML
// failed to parse there is no executable call to report. A true length stop is
// preserved so callers can still distinguish truncation; everything else
// becomes an ordinary assistant stop.
const char *ember_tool_parse_failure_finish(const char *finish);

// True once the client has received something it would actually render: a
// non-whitespace content byte or a tool_call frame.
//
// This is the invariant behind ds4's refusal to retry a malformed tool call
// inside an open stream (ds4_server.c:11671/11754). ds4 states it as "never
// while streaming", but the reason given is that previously-emitted
// reasoning/content cannot be retracted — which only bites once something was
// emitted. A turn whose entire output was one suppressed tool block has
// delivered nothing, so no turn boundary exists to destroy and the bounded
// recovery is still safe.
//
// Reasoning deltas deliberately do NOT count. They are advisory and clients
// concatenate them, so a recovery attempt appends further reasoning and then a
// valid call, which stays coherent. Whitespace-only content does not count
// either: it renders as nothing.
bool ember_sse_delivered_visible(const ember_sse_stream *st);

// Emit the terminal chunk (finish_reason) + optional usage + `data: [DONE]`.
void ember_sse_finish(ember_sse_stream *st, const char *finish_reason,
                      int prompt_tokens, int completion_tokens, ember_buf *out);

// Emit an `event: error` frame (ds4 sse_error_event) for a mid-stream backend
// or typed model-output failure, followed by `data: [DONE]`.
void ember_sse_error(ember_sse_stream *st, const char *code, const char *detail,
                     bool retry_exhausted, ember_buf *out);

// ── exposed for unit tests ──
// Largest safe content length in raw[start..raw_len): holds back an incomplete
// UTF-8 tail and, with tools, everything from the last '<' in the trailing scan
// window (any marker begins with '<'). Ported from ds4 text_stream_safe_limit.
size_t ember_text_safe_limit(const char *raw, size_t start, size_t raw_len,
                             bool has_tools, bool final);
// Earliest tool-call marker start in `s`, or NULL. Recognizes DeepSeek DSML in
// its full, short (leading '<|' eaten), and ascii-degraded spellings.
const char *ember_find_tool_start(const char *s);
// Byte after the complete end marker matching the earliest opener in `s`, or
// NULL. A closer from another degradation family is not accepted.
const char *ember_find_tool_end(const char *s);

#ifdef __cplusplus
}
#endif

#endif  // EMBER_SSE_H
