services:
  ember:
    image: ember:local
    pull_policy: build
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: release
      network: host
      args:
        EMBER_VERSION: ${EMBER_VERSION:-dev}
        EMBER_VCS_REF: ${EMBER_VCS_REF:-unknown}
