#!/usr/bin/env bash
# Profile Ember's GPU kernels on a gfx1151 host and answer one question:
# is decode bandwidth-bound or compute-bound?
#
# That question decides whether kernel-level work has headroom at all. If decode
# already runs near the ~212 GB/s measured memory roofline, no amount of
# instruction scheduling in the matmul kernels moves end-to-end throughput, and
# the useful work is fusion (fewer passes over the weights) or quantization.
# Ember's culture is MEASURED, not assumed -- see the HIP-graph-replay comment in
# engine/CMakeLists.txt, where replay stays off on measured gfx1151 evidence.
#
# MUST run on the gfx1151 host. It needs /dev/kfd, /dev/dri, and a ROCm image
# carrying rocprofv3. It takes exclusive GPU access, so it quiesces production
# through the same fixed-purpose wrapper certification uses
# (/usr/local/sbin/ember-cert-production) and restores it on every exit path,
# including failure and SIGINT. Stopping the production *container* alone is not
# enough: systemd recreates the ~90 GiB process mid-run.
#
#   scripts/profile_gpu.sh --dry-run                 # print the plan, touch nothing
#   scripts/profile_gpu.sh --model /models/model.gguf
#
# Output lands in --out-dir (default ./reports/profile-<UTC stamp>/) as
# rocprofv3 CSVs plus manifest.json. Feed that directory to
# scripts/profile_report.py for the roofline verdict.
#
# Methodology, and why it is shaped this way:
#
#   * Two passes. Kernel timing and hardware counters are collected in SEPARATE
#     runs because counter collection serializes dispatches -- durations taken
#     from a --pmc run understate real throughput and must never be used for the
#     bandwidth denominator.
#   * Phase isolation by idle gap. Prefill and decode are separated by driving
#     warmup, sleeping past --gap-secs, then issuing exactly one shaped request.
#     The analyzer segments the dispatch stream on gaps and takes the last
#     segment. This needs no clock-domain alignment between the client and the
#     profiler, and it is self-checking: the analyzer reports every segment it
#     found so a human can confirm the split is real.
#   * Prefill is a long prompt with max_tokens=1; decode is a short prompt with
#     many tokens. Batch-1 decode re-reads the active weights once per token
#     (arithmetic intensity ~1); prefill amortizes each weight read across the
#     whole prompt. They are different regimes and must be measured apart.
set -euo pipefail

MODEL="${EMBER_PROFILE_MODEL:-}"
DRAFT="${EMBER_PROFILE_DRAFT:-}"
IMAGE="${EMBER_PROFILE_IMAGE:-ember-rocm:7.14-dev}"
BINARY="${EMBER_PROFILE_BINARY:-/ember/build-rocm/ember-dflash}"
PORT="${EMBER_PROFILE_PORT:-18081}"
PRODUCTION_CONTAINER="${EMBER_PRODUCTION_CONTAINER:-ember-server}"
PRODUCTION_WRAPPER="/usr/local/sbin/ember-cert-production"
OUT_DIR=""
PREFILL_WORDS="${EMBER_PROFILE_PREFILL_WORDS:-6000}"
DECODE_TOKENS="${EMBER_PROFILE_DECODE_TOKENS:-256}"
GAP_SECS="${EMBER_PROFILE_GAP_SECS:-3}"
DRY_RUN=0
QUIESCE=1

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

die() { printf 'profile: %s\n' "$*" >&2; exit 1; }
log() { printf 'profile: %s\n' "$*"; }

usage() {
  sed -n '2,/^set -euo/p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//; $d'
  cat <<'EOF'

options:
  --model PATH         target GGUF (required unless --dry-run)
  --draft PATH         DSpark drafter GGUF; enables speculative decode
  --image REF          ROCm image carrying rocprofv3 (default ember-rocm:7.14-dev)
  --binary PATH        ember-dflash path inside the container
  --port N             port for the profiled instance (default 18081)
  --out-dir DIR        output directory (default reports/profile-<UTC stamp>)
  --prefill-words N    words in the prefill probe prompt (default 6000)
  --decode-tokens N    tokens generated by the decode probe (default 256)
  --gap-secs N         idle gap used to segment phases (default 3)
  --no-quiesce         do not stop production (only when nothing is serving)
  --dry-run            print the plan and exit without touching the GPU
  -h, --help           this text
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --model) MODEL="${2:?--model needs a path}"; shift 2 ;;
    --draft) DRAFT="${2:?--draft needs a path}"; shift 2 ;;
    --image) IMAGE="${2:?--image needs a ref}"; shift 2 ;;
    --binary) BINARY="${2:?--binary needs a path}"; shift 2 ;;
    --port) PORT="${2:?--port needs a number}"; shift 2 ;;
    --out-dir) OUT_DIR="${2:?--out-dir needs a path}"; shift 2 ;;
    --prefill-words) PREFILL_WORDS="${2:?--prefill-words needs a number}"; shift 2 ;;
    --decode-tokens) DECODE_TOKENS="${2:?--decode-tokens needs a number}"; shift 2 ;;
    --gap-secs) GAP_SECS="${2:?--gap-secs needs a number}"; shift 2 ;;
    --no-quiesce) QUIESCE=0; shift ;;
    --dry-run) DRY_RUN=1; shift ;;
    -h|--help) usage; exit 0 ;;
    *) die "unknown option: $1 (try --help)" ;;
  esac
done

[[ "$PORT" =~ ^[0-9]+$ ]] && (( PORT >= 1024 && PORT <= 65535 )) \
  || die "--port must be 1024..65535, got '$PORT'"
[[ "$PREFILL_WORDS" =~ ^[0-9]+$ ]] && (( PREFILL_WORDS > 0 )) \
  || die "--prefill-words must be a positive integer"
[[ "$DECODE_TOKENS" =~ ^[0-9]+$ ]] && (( DECODE_TOKENS > 0 )) \
  || die "--decode-tokens must be a positive integer"
[[ "$GAP_SECS" =~ ^[0-9]+$ ]] && (( GAP_SECS >= 1 )) \
  || die "--gap-secs must be >= 1"

if [[ -z "$OUT_DIR" ]]; then
  OUT_DIR="$REPO/reports/profile-$(date -u +%Y%m%dT%H%M%SZ)"
fi

# ── preflight ────────────────────────────────────────────────────────────
# Every check that can run without the GPU runs even under --dry-run, so the
# plan printed below is a plan that would actually work.
preflight_soft() {
  local problems=0
  [[ -n "$MODEL" ]] || { log "MISSING --model (required for a real run)"; problems=1; }
  if [[ -n "$MODEL" && "$MODEL" != /* ]]; then
    log "--model must be absolute (bind-mounted into the container): $MODEL"
    problems=1
  fi
  if [[ -n "$DRAFT" && "$DRAFT" != /* ]]; then
    log "--draft must be absolute: $DRAFT"; problems=1
  fi
  return "$problems"
}

preflight_hard() {
  [[ -r /dev/kfd && -d /dev/dri ]] \
    || die "no /dev/kfd or /dev/dri -- this must run on the gfx1151 host, not a dev box"
  command -v docker >/dev/null || die "docker is required"
  command -v curl >/dev/null || die "curl is required"
  command -v python3 >/dev/null || die "python3 is required"
  [[ -f "$MODEL" ]] || die "model not found: $MODEL"
  [[ -z "$DRAFT" || -f "$DRAFT" ]] || die "draft not found: $DRAFT"

  if grep -Eq '(^| )(iommu|amd_iommu)=off( |$)' /proc/cmdline; then
    die "IOMMU is disabled in the kernel command line"
  fi

  if curl --fail --silent --max-time 2 "http://127.0.0.1:$PORT/health" >/dev/null 2>&1; then
    die "port $PORT already serves a health endpoint; pick another --port"
  fi

  docker image inspect "$IMAGE" >/dev/null 2>&1 \
    || die "image not present: $IMAGE (build it with: docker build --target dev -f docker/Dockerfile -t $IMAGE .)"

  # rocprofv3 must exist *inside* the image; the host does not need it.
  docker run --rm --entrypoint /bin/sh "$IMAGE" -c 'command -v rocprofv3' >/dev/null 2>&1 \
    || die "rocprofv3 not found in $IMAGE -- the profiler lives in the ROCm dev stage"
}

# ── production quiesce, with unconditional restore ───────────────────────
RESTORE_MODE=none

quiesce_production() {
  (( QUIESCE )) || { log "quiesce skipped (--no-quiesce)"; return 0; }
  if sudo -n "$PRODUCTION_WRAPPER" is-active >/dev/null 2>&1; then
    RESTORE_MODE=service
    log "stopping production via $PRODUCTION_WRAPPER"
    sudo -n "$PRODUCTION_WRAPPER" stop
  elif docker inspect "$PRODUCTION_CONTAINER" >/dev/null 2>&1 &&
       [[ "$(docker inspect --format '{{.State.Running}}' "$PRODUCTION_CONTAINER")" == true ]]; then
    # No supervising unit: the container is the whole deployment here.
    RESTORE_MODE=container
    log "stopping production container $PRODUCTION_CONTAINER"
    docker stop --timeout 180 "$PRODUCTION_CONTAINER" >/dev/null
  else
    log "no running production instance found"
    return 0
  fi
  if docker inspect "$PRODUCTION_CONTAINER" >/dev/null 2>&1 &&
     [[ "$(docker inspect --format '{{.State.Running}}' "$PRODUCTION_CONTAINER")" == true ]]; then
    die "production remained active after quiesce request"
  fi
}

restore_production() {
  case "$RESTORE_MODE" in
    service)   log "restoring production service";   sudo -n "$PRODUCTION_WRAPPER" start || true ;;
    container) log "restoring production container"; docker start "$PRODUCTION_CONTAINER" >/dev/null || true ;;
    none)      : ;;
  esac
  RESTORE_MODE=none
}

PROFILE_CONTAINER=""
cleanup() {
  local rc=$?
  if [[ -n "$PROFILE_CONTAINER" ]]; then
    docker rm -f "$PROFILE_CONTAINER" >/dev/null 2>&1 || true
    PROFILE_CONTAINER=""
  fi
  restore_production
  exit "$rc"
}

# ── workload probes ──────────────────────────────────────────────────────
# Prefill probe: long prompt, one token out. Decode probe: short prompt, many
# tokens out. Both are temperature 0 so a rerun is comparable.
write_probes() {
  local dir="$1"
  python3 - "$dir" "$PREFILL_WORDS" "$DECODE_TOKENS" <<'PY'
import json, sys
out, words, decode_tokens = sys.argv[1], int(sys.argv[2]), int(sys.argv[3])
filler = " ".join(
    f"Segment {i} carries deterministic profiling context." for i in range(words // 6 + 1)
)
def body(prompt, max_tokens):
    return {
        "model": "deepseek-v4-flash",
        "messages": [{"role": "user", "content": prompt}],
        "max_tokens": max_tokens,
        "temperature": 0,
        "stream": False,
    }
with open(f"{out}/probe-warmup.json", "w") as fh:
    json.dump(body("Reply with only: warm", 8), fh)
with open(f"{out}/probe-prefill.json", "w") as fh:
    json.dump(body(filler + "\n\nReply with only: ok", 1), fh)
with open(f"{out}/probe-decode.json", "w") as fh:
    json.dump(body("Count upward from one, one number per line.", decode_tokens), fh)
PY
}

# ── one profiled run ─────────────────────────────────────────────────────
# mode=trace  -> kernel timing (durations are trustworthy)
# mode=pmc    -> hardware counters (durations are NOT trustworthy: serialized)
# MEASURED on gfx1151 (2026-08-22): requesting FETCH_SIZE and WRITE_SIZE in one
# --pmc pass fails with "error code 38: Request exceeds the capabilities of the
# hardware to collect" and rocprofv3 then SIGSEGVs (exit 139) instead of
# reporting it -- no CSV, no diagnostic in the normal output. One counter per
# pass always works. Do NOT "optimize" these back into a single invocation.
run_pass() {
  local mode="$1" phase="$2" outdir="$3" counter="${4:-}"
  local tag="$mode-$phase${counter:+-$counter}"
  local name="ember-profile-$tag-$$"
  local prof=(rocprofv3 --output-format csv -d /out -o "$tag")

  case "$mode" in
    trace) prof+=(--kernel-trace --stats) ;;
    pmc)   [[ -n "$counter" ]] || die "pmc pass needs exactly one counter"
           prof+=(--pmc "$counter" --kernel-trace) ;;
    *)     die "unknown pass mode: $mode" ;;
  esac

  local gpu_args=(
    --device /dev/kfd --device /dev/dri
    --group-add video --group-add render
    --ipc host --security-opt seccomp=unconfined
    --ulimit memlock=-1:-1
  )
  local mounts=(
    -v "$REPO:/ember"
    -v "$outdir:/out"
    -v "$(dirname -- "$MODEL"):/pmodel:ro"
  )
  local env_args=()
  local model_arg="/pmodel/$(basename -- "$MODEL")"
  if [[ -n "$DRAFT" ]]; then
    mounts+=(-v "$(dirname -- "$DRAFT"):/pdraft:ro")
    env_args+=(-e DFLASH_DS4_SPEC=1 -e "DFLASH_DS4_DRAFT=/pdraft/$(basename -- "$DRAFT")")
  fi
  # Idle graph reclaim would free compute graphs mid-measurement and charge the
  # next request a rebuild, which shows up as phantom kernel time.
  env_args+=(-e EMBER_IDLE_RECLAIM_SECS=0)

  # Pass rocprofv3 and its target as argv rather than a shell string: a model
  # path with a space would otherwise split and start a server on the wrong file.
  PROFILE_CONTAINER="$name"
  docker run -d --name "$name" --network host "${gpu_args[@]}" "${mounts[@]}" "${env_args[@]}" \
    --entrypoint rocprofv3 "$IMAGE" \
    "${prof[@]:1}" \
    -- "$BINARY" -m "$model_arg" --host 127.0.0.1 --port "$PORT" --max-ctx 65536 \
    >/dev/null

  log "  [$tag] waiting for model load (this takes minutes)"
  local waited=0
  until curl --fail --silent --max-time 2 "http://127.0.0.1:$PORT/health" >/dev/null 2>&1; do
    docker inspect --format '{{.State.Running}}' "$name" 2>/dev/null | grep -q true \
      || { docker logs --tail 40 "$name" >&2 || true; die "profiled server exited during load"; }
    sleep 5; waited=$((waited + 5))
    (( waited < 1800 )) || die "server did not become healthy within 30 minutes"
  done

  # Warmup builds the compute graphs. Its kernels belong to no measured phase.
  curl --fail --silent --max-time 300 -H 'Content-Type: application/json' \
    -d "@$outdir/probe-warmup.json" "http://127.0.0.1:$PORT/v1/chat/completions" >/dev/null

  # The gap is the phase delimiter the analyzer segments on.
  sleep "$GAP_SECS"

  log "  [$tag] issuing measured request"
  curl --fail --silent --max-time 900 -H 'Content-Type: application/json' \
    -d "@$outdir/probe-$phase.json" "http://127.0.0.1:$PORT/v1/chat/completions" \
    >"$outdir/response-$mode-$phase.json"

  sleep "$GAP_SECS"

  # SIGINT lets rocprofv3 flush its buffers; docker kill would truncate the CSV.
  docker stop --timeout 120 "$name" >/dev/null
  docker rm -f "$name" >/dev/null 2>&1 || true
  PROFILE_CONTAINER=""
}

# ── counter selection ────────────────────────────────────────────────────
# Never hardcode a counter set: availability differs across ROCm releases and
# gfx targets, and a silently-missing counter yields a bandwidth number with no
# denominator. Ask the image what it has, and record the choice in the manifest.
PMC_COUNTERS=()
select_counters() {
  local avail
  avail="$(docker run --rm --entrypoint /bin/sh "$IMAGE" -c 'rocprofv3 --list-avail 2>/dev/null' || true)"
  local want=(FETCH_SIZE WRITE_SIZE)
  local missing=()
  for c in "${want[@]}"; do
    if grep -qw "$c" <<<"$avail"; then PMC_COUNTERS+=("$c"); else missing+=("$c"); fi
  done
  if (( ${#PMC_COUNTERS[@]} == 0 )); then
    die "none of ${want[*]} are available in $IMAGE; run 'rocprofv3 --list-avail' and set the counters by hand"
  fi
  (( ${#missing[@]} == 0 )) || log "counters unavailable, bandwidth will be partial: ${missing[*]}"
}

# ── plan ─────────────────────────────────────────────────────────────────
print_plan() {
  cat <<EOF
plan:
  host GPU        /dev/kfd + /dev/dri (gfx1151)
  image           $IMAGE
  binary          $BINARY
  model           ${MODEL:-<unset>}
  draft           ${DRAFT:-<none> (DSpark off)}
  port            $PORT
  out-dir         $OUT_DIR
  phase gap       ${GAP_SECS}s
  prefill probe   ~$PREFILL_WORDS words, max_tokens=1
  decode probe    short prompt, max_tokens=$DECODE_TOKENS
  production      $( ((QUIESCE)) && echo "quiesce via $PRODUCTION_WRAPPER, restore on every exit" || echo "left alone (--no-quiesce)" )
  passes          trace x2 phases, then one pmc pass PER COUNTER per phase
                  (gfx1151 SIGSEGVs if two counters share a pass)
  analysis        scripts/profile_report.py $OUT_DIR
EOF
}

main() {
  preflight_soft || (( DRY_RUN )) || die "fix the problems above, or use --dry-run"
  print_plan
  if (( DRY_RUN )); then
    log "dry run: nothing was started, no GPU touched"
    return 0
  fi

  preflight_hard
  mkdir -p "$OUT_DIR"
  write_probes "$OUT_DIR"
  select_counters
  log "counters: ${PMC_COUNTERS[*]}"

  trap cleanup EXIT INT TERM
  quiesce_production

  for phase in prefill decode; do
    log "pass trace/$phase"
    run_pass trace "$phase" "$OUT_DIR"
  done
  for phase in prefill decode; do
    for counter in "${PMC_COUNTERS[@]}"; do
      log "pass pmc/$phase/$counter"
      run_pass pmc "$phase" "$OUT_DIR" "$counter"
    done
  done

  python3 - "$OUT_DIR" "${PMC_COUNTERS[@]}" <<'PY'
import json, sys, os
out = sys.argv[1]
json.dump({
    "counters": sys.argv[2:],
    "note": "durations are valid only in trace-* passes; pmc-* passes serialize dispatches",
    "passes": sorted(f for f in os.listdir(out) if f.endswith(".csv")),
}, open(os.path.join(out, "manifest.json"), "w"), indent=2)
PY

  trap - EXIT INT TERM
  restore_production

  log "done -> $OUT_DIR"
  log "next: scripts/profile_report.py $OUT_DIR"
}

main "$@"
