#!/usr/bin/env python3
"""Regenerate deterministic Unicode tables for the Qwen tokenizer scanner.

The runtime intentionally has no locale, ICU, or Python dependency. This
stdlib-only generator turns Python's pinned Unicode database into compact
category/NFC tables consumed by pre_tokenizer.cpp. Run it with the repository
root as the working directory after intentionally updating Unicode semantics.
"""

from __future__ import annotations

from pathlib import Path
import unicodedata


OUT = Path("engine/dflash/server/qwen_unicode_tables.inc")


def ranges_for(prefix: str) -> list[tuple[int, int]]:
    points = [cp for cp in range(0x110000)
              if unicodedata.category(chr(cp)).startswith(prefix)]
    result: list[tuple[int, int]] = []
    start = previous = points[0]
    for cp in points[1:]:
        if cp == previous + 1:
            previous = cp
            continue
        result.append((start, previous))
        start = previous = cp
    result.append((start, previous))
    return result


def emit_array(lines: list[str], ctype: str, name: str,
               rows: list[str]) -> None:
    lines.append(f"static constexpr {ctype} {name}[] = {{")
    lines.extend(f"    {row}," for row in rows)
    lines.append("};")
    lines.append("")


def main() -> None:
    decomp_values: list[int] = []
    decompositions: list[tuple[int, int, int]] = []
    compositions: list[tuple[int, int, int]] = []
    ccc: list[tuple[int, int]] = []

    for cp in range(0x110000):
        char = chr(cp)
        combining = unicodedata.combining(char)
        if combining:
            ccc.append((cp, combining))
        raw = unicodedata.decomposition(char)
        if not raw or raw.startswith("<"):
            continue
        values = [int(value, 16) for value in raw.split()]
        offset = len(decomp_values)
        decomp_values.extend(values)
        decompositions.append((cp, offset, len(values)))
        if (len(values) == 2 and
                unicodedata.normalize("NFC", "".join(map(chr, values))) == char):
            compositions.append((values[0], values[1], cp))

    compositions.sort(key=lambda item: (item[0], item[1]))
    lines = [
        "// Generated by tools/generate_qwen_unicode_tables.py.",
        f"// Python Unicode database: {unicodedata.unidata_version}.",
        "// Do not hand edit; category and NFC behavior are tokenizer state.",
        "",
    ]
    for prefix, name in (("L", "kQwenLetterRanges"),
                         ("M", "kQwenMarkRanges"),
                         ("N", "kQwenNumberRanges")):
        emit_array(lines, "QwenRange", name,
                   [f"{{0x{a:X}, 0x{b:X}}}" for a, b in ranges_for(prefix)])
    emit_array(lines, "QwenCombining", "kQwenCombining",
               [f"{{0x{cp:X}, {value}}}" for cp, value in ccc])
    emit_array(lines, "uint32_t", "kQwenDecompositionValues",
               [f"0x{cp:X}" for cp in decomp_values])
    emit_array(lines, "QwenDecomposition", "kQwenDecompositions",
               [f"{{0x{cp:X}, {offset}, {length}}}"
                for cp, offset, length in decompositions])
    emit_array(lines, "QwenComposition", "kQwenCompositions",
               [f"{{(uint64_t(0x{a:X}) << 21) | 0x{b:X}, 0x{cp:X}}}"
                for a, b, cp in compositions])
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT} ({len(lines)} lines, Unicode {unicodedata.unidata_version})")


if __name__ == "__main__":
    main()
